=== nightcycle/roblox-mesh-universal-standard/schema/mesh-v1.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/nightcycle/roblox-mesh-universal-standard/main/schema/mesh-v1.schema.json",
  "title": "RMUS EditableMesh interchange v1",
  "type": "object",
  "properties": {
    "Format": {
      "const": "roblox-mesh-universal"
    },
    "Version": {
      "type": "object",
      "properties": {
        "Major": {
          "const": 1
        },
        "Minor": {
          "type": "integer",
          "minimum": 0
        }
      },
      "required": [
        "Major",
        "Minor"
      ]
    },
    "RequiredFeatures": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "Vertices": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "number"
        },
        "minItems": 3,
        "maxItems": 3
      },
      "minItems": 1,
      "maxItems": 60000
    },
    "Normals": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "number"
        },
        "minItems": 3,
        "maxItems": 3
      }
    },
    "UVs": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "number"
        },
        "minItems": 2,
        "maxItems": 2
      }
    },
    "Colors": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "number",
          "minimum": 0,
          "maximum": 1
        },
        "minItems": 4,
        "maxItems": 4
      }
    },
    "Faces": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Face"
      },
      "minItems": 1,
      "maxItems": 20000
    },
    "Bones": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Bone"
      }
    },
    "Skin": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Skin"
      }
    },
    "Facs": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Pose"
      }
    },
    "Part": {
      "$ref": "#/$defs/Part"
    },
    "Metadata": {
      "type": "object"
    },
    "Extensions": {
      "type": "object"
    }
  },
  "required": [
    "Format",
    "Version",
    "Vertices",
    "Faces"
  ],
  "$defs": {
    "Face": {
      "type": "object",
      "properties": {
        "Vertices": {
          "type": "array",
          "items": {
            "type": "integer",
            "minimum": 1
          },
          "minItems": 3,
          "maxItems": 4,
          "uniqueItems": true
        },
        "Normals": {
          "type": "array",
          "items": {
            "type": "integer",
            "minimum": 1
          }
        },
        "Colors": {
          "type": "array",
          "items": {
            "type": "integer",
            "minimum": 1
          }
        },
        "UVs": {
          "type": "array",
          "items": {
            "type": "integer",
            "minimum": 1
          }
        }
      },
      "required": [
        "Vertices"
      ]
    },
    "Bone": {
      "type": "object",
      "properties": {
        "Name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 100
        },
        "Parent": {
          "type": "integer",
          "minimum": 1
        },
        "CFrame": {
          "type": "array",
          "items": {
            "type": "number"
          },
          "minItems": 12,
          "maxItems": 12
        },
        "Virtual": {
          "type": "boolean"
        }
      },
      "required": [
        "Name",
        "CFrame"
      ]
    },
    "Skin": {
      "type": "object",
      "properties": {
        "Vertex": {
          "type": "integer",
          "minimum": 1
        },
        "Bones": {
          "type": "array",
          "items": {
            "type": "integer",
            "minimum": 1
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "Weights": {
          "type": "array",
          "items": {
            "type": "number",
            "minimum": 0,
            "maximum": 1
          }
        }
      },
      "required": [
        "Vertex",
        "Bones",
        "Weights"
      ]
    },
    "Pose": {
      "type": "object",
      "properties": {
        "Actions": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "minItems": 1,
          "maxItems": 3,
          "uniqueItems": true
        },
        "Bones": {
          "type": "array",
          "items": {
            "type": "integer",
            "minimum": 1
          },
          "uniqueItems": true
        },
        "CFrames": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "number"
            },
            "minItems": 12,
            "maxItems": 12
          }
        }
      },
      "required": [
        "Actions",
        "Bones",
        "CFrames"
      ]
    },
    "Part": {
      "type": "object",
      "properties": {
        "Name": {
          "type": "string"
        },
        "Size": {
          "type": "array",
          "items": {
            "type": "number",
            "exclusiveMinimum": 0
          },
          "minItems": 3,
          "maxItems": 3
        },
        "CFrame": {
          "type": "array",
          "items": {
            "type": "number"
          },
          "minItems": 12,
          "maxItems": 12
        },
        "PivotOffset": {
          "type": "array",
          "items": {
            "type": "number"
          },
          "minItems": 12,
          "maxItems": 12
        },
        "Color": {
          "type": "array",
          "items": {
            "type": "number",
            "minimum": 0,
            "maximum": 1
          },
          "minItems": 3,
          "maxItems": 3
        },
        "Transparency": {
          "type": "number",
          "minimum": 0,
          "maximum": 1
        },
        "Reflectance": {
          "type": "number",
          "minimum": 0,
          "maximum": 1
        },
        "MaterialVariant": {
          "type": "string"
        },
        "Anchored": {
          "type": "boolean"
        },
        "CanCollide": {
          "type": "boolean"
        },
        "CanTouch": {
          "type": "boolean"
        },
        "CanQuery": {
          "type": "boolean"
        },
        "CastShadow": {
          "type": "boolean"
        },
        "DoubleSided": {
          "type": "boolean"
        },
        "Material": {
          "type": "integer",
          "minimum": 0
        },
        "CollisionFidelity": {
          "type": "integer",
          "minimum": 0
        },
        "RenderFidelity": {
          "type": "integer",
          "minimum": 0
        },
        "Attributes": {
          "type": "object"
        },
        "Tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "Name",
        "Size",
        "CFrame",
        "PivotOffset",
        "Color",
        "Transparency",
        "Reflectance",
        "MaterialVariant",
        "Anchored",
        "CanCollide",
        "CanTouch",
        "CanQuery",
        "CastShadow",
        "DoubleSided",
        "Material",
        "CollisionFidelity",
        "RenderFidelity"
      ]
    }
  }
}

=== nightcycle/roblox-mesh-universal-standard/demo/assets/grass.json
{"Format":"roblox-mesh-universal","Version":{"Major":1,"Minor":0},"RequiredFeatures":["geometry","normals","colors","uvs"],"Vertices":[[-0.05307007,-0.004214287,-0.09772873],[-0.069381714,0.0123384,-0.058475494],[-0.122612,0.034463644,-0.11565018],[0.00289917,-0.08708683,0.042915344],[0.043792725,-0.12574244,-0.01908493],[0.032432556,-0.051359594,0.040122986],[-0.069381714,0.0123384,-0.058475494],[-0.0398407,0.048066854,-0.061267853],[-0.122612,0.034463644,-0.11565018],[0.07331848,-0.090014815,-0.021877289],[-0.05307007,-0.004214287,-0.09772873],[-0.023529053,0.031513445,-0.10052109],[-0.122612,0.034463644,-0.11565018],[-0.023529053,0.031513445,-0.10052109],[-0.0398407,0.048066854,-0.061267853],[-0.122612,0.034463644,-0.11565018],[-0.020339966,0.05098176,0.03277588],[-0.050598145,0.026382446,0.056430817],[-0.045692444,0.107797146,0.11565399],[-0.011367798,-0.108009756,0.026668549],[0.04902649,-0.07795067,-0.02294159],[0.01927948,-0.11241627,0.06129074],[-0.019966125,0.02197671,0.09105301],[-0.050598145,0.026382446,0.056430817],[-0.045692444,0.107797146,0.11565399],[0.07965851,-0.08235644,0.011684418],[0.010299683,0.046575308,0.06739807],[-0.019966125,0.02197671,0.09105301],[-0.045692444,0.107797146,0.11565399],[0.010299683,0.046575308,0.06739807],[-0.020339966,0.05098176,0.03277588],[-0.045692444,0.107797146,0.11565399],[0.090911865,0.08492041,-0.009544373],[0.05482483,0.08394003,0.018333435],[0.12260437,0.12574244,0.06612396],[0.01663971,-0.07429452,-0.0004119873],[0.077445984,-0.087896615,-0.056346893],[0.042755127,-0.09374994,0.032699585],[0.08094025,0.06448507,0.051448822],[0.05482483,0.08394003,0.018333435],[0.12260437,0.12574244,0.06612396],[0.10355377,-0.1073513,-0.023231506],[0.11701965,0.06546497,0.0235672],[0.08094025,0.06448507,0.051448822],[0.12260437,0.12574244,0.06612396],[0.11701965,0.06546497,0.0235672],[0.090911865,0.08492041,-0.009544373],[0.12260437,0.12574244,0.06612396]],"Faces":[{"Vertices":[1,2,3],"Normals":[1,2,3],"Colors":[1,2,3],"UVs":[1,2,3]},{"Vertices":[1,4,2],"Normals":[1,4,2],"Colors":[1,4,2],"UVs":[1,4,2]},{"Vertices":[5,4,1],"Normals":[5,4,1],"Colors":[5,4,1],"UVs":[5,4,1]},{"Vertices":[5,6,4],"Normals":[5,6,4],"Colors":[5,6,4],"UVs":[5,6,4]},{"Vertices":[4,6,7],"Normals":[4,6,7],"Colors":[4,6,7],"UVs":[4,6,7]},{"Vertices":[7,6,8],"Normals":[7,6,8],"Colors":[7,6,8],"UVs":[7,6,8]},{"Vertices":[7,8,9],"Normals":[7,8,9],"Colors":[7,8,9],"UVs":[7,8,9]},{"Vertices":[10,6,5],"Normals":[10,6,5],"Colors":[10,6,5],"UVs":[10,6,5]},{"Vertices":[5,11,10],"Normals":[5,11,10],"Colors":[5,11,10],"UVs":[5,11,10]},{"Vertices":[10,11,12],"Normals":[10,11,12],"Colors":[10,11,12],"UVs":[10,11,12]},{"Vertices":[12,11,13],"Normals":[12,11,13],"Colors":[12,11,13],"UVs":[12,11,13]},{"Vertices":[14,6,10],"Normals":[14,6,10],"Colors":[14,6,10],"UVs":[14,6,10]},{"Vertices":[15,6,14],"Normals":[15,6,14],"Colors":[15,6,14],"UVs":[15,6,14]},{"Vertices":[16,15,14],"Normals":[16,15,14],"Colors":[16,15,14],"UVs":[16,15,14]},{"Vertices":[17,18,19],"Normals":[17,18,19],"Colors":[17,18,19],"UVs":[17,18,19]},{"Vertices":[17,20,18],"Normals":[17,20,18],"Colors":[17,20,18],"UVs":[17,20,18]},{"Vertices":[21,20,17],"Normals":[21,20,17],"Colors":[21,20,17],"UVs":[21,20,17]},{"Vertices":[21,22,20],"Normals":[21,22,20],"Colors":[21,22,20],"UVs":[21,22,20]},{"Vertices":[22,23,20],"Normals":[22,23,20],"Colors":[22,23,20],"UVs":[22,23,20]},{"Vertices":[20,23,24],"Normals":[20,23,24],"Colors":[20,23,24],"UVs":[20,23,24]},{"Vertices":[24,23,25],"Normals":[24,23,25],"Colors":[24,23,25],"UVs":[24,23,25]},{"Vertices":[26,22,21],"Normals":[26,22,21],"Colors":[26,22,21],"UVs":[26,22,21]},{"Vertices":[27,22,26],"Normals":[27,22,26],"Colors":[27,22,26],"UVs":[27,22,26]},{"Vertices":[28,22,27],"Normals":[28,22,27],"Colors":[28,22,27],"UVs":[28,22,27]},{"Vertices":[29,28,27],"Normals":[29,28,27],"Colors":[29,28,27],"UVs":[29,28,27]},{"Vertices":[26,21,30],"Normals":[26,21,30],"Colors":[26,21,30],"UVs":[26,21,30]},{"Vertices":[30,21,31],"Normals":[30,21,31],"Colors":[30,21,31],"UVs":[30,21,31]},{"Vertices":[30,31,32],"Normals":[30,31,32],"Colors":[30,31,32],"UVs":[30,31,32]},{"Vertices":[33,34,35],"Normals":[33,34,35],"Colors":[33,34,35],"UVs":[33,34,35]},{"Vertices":[33,36,34],"Normals":[33,36,34],"Colors":[33,36,34],"UVs":[33,36,34]},{"Vertices":[37,36,33],"Normals":[37,36,33],"Colors":[37,36,33],"UVs":[37,36,33]},{"Vertices":[37,38,36],"Normals":[37,38,36],"Colors":[37,38,36],"UVs":[37,38,36]},{"Vertices":[38,39,36],"Normals":[38,39,36],"Colors":[38,39,36],"UVs":[38,39,36]},{"Vertices":[36,39,40],"Normals":[36,39,40],"Colors":[36,39,40],"UVs":[36,39,40]},{"Vertices":[40,39,41],"Normals":[40,39,41],"Colors":[40,39,41],"UVs":[40,39,41]},{"Vertices":[42,38,37],"Normals":[42,38,37],"Colors":[42,38,37],"UVs":[42,38,37]},{"Vertices":[43,38,42],"Normals":[43,38,42],"Colors":[43,38,42],"UVs":[43,38,42]},{"Vertices":[44,38,43],"Normals":[44,38,43],"Colors":[44,38,43],"UVs":[44,38,43]},{"Vertices":[45,44,43],"Normals":[45,44,43],"Colors":[45,44,43],"UVs":[45,44,43]},{"Vertices":[42,37,46],"Normals":[42,37,46],"Colors":[42,37,46],"UVs":[42,37,46]},{"Vertices":[46,37,47],"Normals":[46,37,47],"Colors":[46,37,47],"UVs":[46,37,47]},{"Vertices":[46,47,48],"Normals":[46,47,48],"Colors":[46,47,48],"UVs":[46,47,48]}],"Normals":[[-0.7163395,-0.697414,-0.02171127],[-0.71668833,-0.6973836,-0.003739887],[-0.50933975,-0.8480924,0.14598766],[-0.73062223,-0.5308243,0.42943773],[-0.3288704,-0.8804258,-0.34160608],[0.5018817,0.62756526,0.5952114],[-0.48784512,0.4612275,0.7411318],[-0.48308018,0.4576963,0.74642324],[-0.5326834,0.49407792,0.68712115],[0.93426156,0.20251836,-0.29349905],[0.26031107,-0.28732848,-0.9217811],[0.27213174,-0.29661936,-0.91540223],[0.14244172,-0.19370383,-0.9706643],[0.6210966,0.7819027,-0.05354582],[0.6032969,0.79310936,-0.0837283],[0.08235398,0.93008864,-0.35798463],[-0.6792869,0.12591742,-0.7229897],[-0.6828122,0.15308611,-0.7143753],[-0.7457554,0.42073807,-0.51655436],[-0.8066923,-0.426996,-0.4085609],[-0.074516,0.052403275,-0.995842],[0.2747748,-0.4278989,0.8610467],[-0.72142196,-0.3579279,0.5928221],[-0.7216345,-0.35701686,0.5931126],[-0.71566916,-0.38211673,0.5846405],[0.9537105,0.022725677,0.2998664],[0.62582284,-0.005356399,0.77994686],[0.61990947,-0.008148185,0.7846311],[0.63180894,-0.032588188,0.77443886],[0.6113932,0.6446388,-0.45895442],[0.6143068,0.6395451,-0.46217877],[0.5245768,0.7685003,-0.36636922],[-0.5667314,0.4392265,-0.6970621],[-0.55029154,0.46118736,-0.69604987],[-0.29743582,0.88676757,-0.35380107],[-0.94476825,0.047904123,-0.32421938],[-0.10548273,0.023145763,-0.9941517],[0.14324161,-0.40874532,0.9013374],[-0.7270182,0.16053171,0.6675883],[-0.73230934,0.14838424,0.66460896],[-0.6636748,0.28584737,0.6912503],[0.86456925,-0.42175043,0.2732152],[0.5978653,-0.30307874,0.7420919],[0.5871661,-0.3064337,0.7492225],[0.53062284,-0.521114,0.6684906],[0.81669694,0.14565416,-0.55838245],[0.8148366,0.13340099,-0.5641325],[0.82687896,0.27120453,-0.4926655]],"Colors":[[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0]],"UVs":[[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943],[0.056958497,0.38708943]],"Bones":[],"Skin":[],"Facs":[],"Part":{"Name":"Meshes/PolygonNature_Plant_Grass_01","Size":[0.24521637,0.25148487,0.23130417],"CFrame":[466.72693,0.040509284,-317.65656,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],"Color":[0.6392157,0.63529414,0.64705884],"Transparency":0.0,"Reflectance":0.0,"Material":256,"MaterialVariant":"","Anchored":true,"CanCollide":true,"CanTouch":true,"CanQuery":true,"CastShadow":true,"DoubleSided":false,"CollisionFidelity":0,"RenderFidelity":1,"PivotOffset":[0.0,-0.040509284,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],"Attributes":{},"Tags":[]},"Metadata":{"Source":"test/grass.rbxm","SourceMesh":"rbxassetid://6341641313","lodOffsets":[0,0],"robloxMeshVersion":"version 4.00","sourceFaceCount":42},"Extensions":{}}
